### ISSUE TITLE
laravel-mix not working

### ISSUE THREAD

**Issue by sahrullahh** [Degovan/vue-spillmoment#18]

**Comment by sahrullahh** [comment]
@destroylord  masih belum bisa nih yaapa ya

**Comment by sahrullahh** [comment]
mungkin bang @irsyadulibad atau @mcoded17  bisa bantu juga

**Comment by destroylord** [comment]
> @destroylord masih belum bisa nih yaapa ya

Udah di pull belom?

**Comment by sahrullahh** [comment]
udah mas
